[package]
name = "winmine"
version = "0.1.0"
edition = "2024"
publish = false

[profile.dev]
incremental = true

[profile.release]
lto = true
codegen-units = 1

[dependencies]
windows-sys = { version = "0.61.2", features = [
	"Win32_Media_Audio",
	"Win32_Graphics_Gdi",
	"Win32_UI_WindowsAndMessaging",
	"Win32_System_WindowsProgramming",
	"Win32_Data_HtmlHelp",
] }

[dependencies.winsafe]
git = "https://github.com/rodrigocfd/winsafe.git"
rev = "45efa9c37a1b428ddcb131411d9e488a9acd0caf"
features = [
	"advapi",
	"comctl",
	"dshow",
	"dwm",
	"dxgi",
	"gdi",
	"gui",
	"kernel",
	"mf",
	"ole",
	"oleaut",
	"psapi",
	"raw-dylib",
	"shell",
	"taskschd",
	"user",
	"uxtheme",
	"version",
	"wininet",
	"winspool"
]

[build-dependencies]
embed-resource = "3.0.6"
